### ISSUE TITLE
Hardcoded Please correct the errors message

### ISSUE THREAD

**Issue by yhortuk** [kompo/vue-kompo#3]
There is hardcoded message on validation error. It should be somewhat configurable for proper integration into localizable projects.
https://github.com/kompo/vue-kompo/blob/73226758d2c266fde55b104acad3cb5e7373d9a3/js/form/FormInner.vue#L80

**Comment by kompo** [comment]
You also need to update to latest backend version of the package.

Usage: 

**For all Forms**
Translate the key "Please correct the errors" in lang.json file. Ex: fr.json:

`"Please correct the errors": "SVP corriger les erreurs"`

**For specific Form**
Add class property $validationErrorAlert:

`protected $validationErrorAlert = 'This is a custom error message';`
